bind_address = "0.0.0.0:25565"
motd = "Minecraft High Performance Redstone Server"
chat_format = "<{username}> {message}"
max_players = 99999
view_distance = 8
whitelist = false
schemati = false
block_in_hitbox = true
auto_redpiler = false
lua_script_path = "./plugin_loader.lua"
lua_enable_sandbox = true